# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "haproxy"
    v.memory = 256
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "haproxy"
  config.vm.network :private_network, ip: "192.168.33.27"

  config.vm.define :haproxy do |haproxy|
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "haproxy.yml"
    ansible.inventory_path = "inventory"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3",
     }
  end

end